"
## Relations
======================

### Parents
| Relation | Origin | Opposite | Type | Comment |
|---|
| `adjacentSiblingSelectorOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSAdjacentSiblingSelector` | |
| `argumentValueOwner` | `FASTSCSSEntity` | `value` | `FASTSCSSArgument` | |
| `argumentsOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSArguments` | |
| `atRootStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSAtRootStatement` | |
| `atRuleOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSAtRule` | |
| `attributeNameOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSAttributeName` | |
| `attributeSelectorOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSAttributeSelector` | |
| `binaryExpressionOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSBinaryExpression` | |
| `binaryQueryOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSBinaryQuery` | |
| `blockOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSBlock` | |
| `callExpressionOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSCallExpression` | |
| `charsetStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSCharsetStatement` | |
| `childSelectorOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSChildSelector` | |
| `classNameOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSClassName` | |
| `classSelectorOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSClassSelector` | |
| `debugStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSDebugStatement` | |
| `declarationOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSDeclaration` | |
| `descendantSelectorOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSDescendantSelector` | |
| `elseClauseOwner` | `FASTSCSSEntity` | `childrenNode` | `FASTSCSSElseClause` | |
| `elseIfClauseConditionOwner` | `FASTSCSSEntity` | `condition` | `FASTSCSSElseIfClause` | |
| `errorStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSErrorStatement` | |
| `extendStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSExtendStatement` | |
| `featureQueryOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSFeatureQuery` | |
| `floatValueOwner` | `FASTSCSSEntity` | `childrenNode` | `FASTSCSSFloatValue` | |
| `forStatementFromOwner` | `FASTSCSSEntity` | `from` | `FASTSCSSForStatement` | |
| `forStatementThroughOwner` | `FASTSCSSEntity` | `through` | `FASTSCSSForStatement` | |
| `forwardStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSForwardStatement` | |
| `genericParent` | `FASTSCSSEntity` | `genericChildren` | `FASTSCSSEntity` | |
| `gridValueOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSGridValue` | |
| `idSelectorOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSIdSelector` | |
| `ifStatementConditionOwner` | `FASTSCSSEntity` | `condition` | `FASTSCSSIfStatement` | |
| `importStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSImportStatement` | |
| `includeStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSIncludeStatement` | |
| `integerValueOwner` | `FASTSCSSEntity` | `childrenNode` | `FASTSCSSIntegerValue` | |
| `interpolationOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSInterpolation` | |
| `keyframeBlockListOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSKeyframeBlockList` | |
| `keyframeBlockOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSKeyframeBlock` | |
| `keyframesStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSKeyframesStatement` | |
| `listValueOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSListValue` | |
| `mediaStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSMediaStatement` | |
| `namespaceSelectorOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSNamespaceSelector` | |
| `namespaceStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSNamespaceStatement` | |
| `parameterDefaultOwner` | `FASTSCSSEntity` | `default` | `FASTSCSSParameter` | |
| `parametersOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSParameters` | |
| `parenthesizedQueryOwner` | `FASTSCSSEntity` | `childrenNode` | `FASTSCSSParenthesizedQuery` | |
| `parenthesizedValueOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSParenthesizedValue` | |
| `placeholderOwner` | `FASTSCSSEntity` | `childrenNode` | `FASTSCSSPlaceholder` | |
| `postcssStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSPostcssStatement` | |
| `propertyNameOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSPropertyName` | |
| `pseudoClassSelectorOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSPseudoClassSelector` | |
| `pseudoElementSelectorOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSPseudoElementSelector` | |
| `returnStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSReturnStatement` | |
| `ruleSetOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSRuleSet` | |
| `selectorQueryOwner` | `FASTSCSSEntity` | `childrenNode` | `FASTSCSSSelectorQuery` | |
| `selectorsOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSSelectors` | |
| `siblingSelectorOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSSiblingSelector` | |
| `stylesheetOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSStylesheet` | |
| `supportsStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSSupportsStatement` | |
| `tagNameOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSTagName` | |
| `unaryQueryOwner` | `FASTSCSSEntity` | `childrenNode` | `FASTSCSSUnaryQuery` | |
| `useStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSUseStatement` | |
| `warnStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSWarnStatement` | |
| `whileStatementOwner` | `FASTSCSSEntity` | `childrenNodes` | `FASTSCSSWhileStatement` | |

### Children
| Relation | Origin | Opposite | Type | Comment |
|---|
| `genericChildren` | `FASTSCSSEntity` | `genericParent` | `FASTSCSSEntity` | |


## Properties
======================

| Name | Type | Default value | Comment |
|---|
| `endPos` | `Number` | nil | |
| `startPos` | `Number` | nil | |

"
Class {
	#name : 'FASTSCSSEntity',
	#superclass : 'MooseEntity',
	#traits : 'FASTTEntity + TEntityMetaLevelDependency',
	#classTraits : 'FASTTEntity classTrait + TEntityMetaLevelDependency classTrait',
	#instVars : [
		'#adjacentSiblingSelectorOwner => FMOne type: #FASTSCSSAdjacentSiblingSelector opposite: #childrenNodes',
		'#argumentValueOwner => FMOne type: #FASTSCSSArgument opposite: #value',
		'#argumentsOwner => FMOne type: #FASTSCSSArguments opposite: #childrenNodes',
		'#atRootStatementOwner => FMOne type: #FASTSCSSAtRootStatement opposite: #childrenNodes',
		'#atRuleOwner => FMOne type: #FASTSCSSAtRule opposite: #childrenNodes',
		'#attributeNameOwner => FMOne type: #FASTSCSSAttributeName opposite: #childrenNodes',
		'#attributeSelectorOwner => FMOne type: #FASTSCSSAttributeSelector opposite: #childrenNodes',
		'#binaryExpressionOwner => FMOne type: #FASTSCSSBinaryExpression opposite: #childrenNodes',
		'#binaryQueryOwner => FMOne type: #FASTSCSSBinaryQuery opposite: #childrenNodes',
		'#blockOwner => FMOne type: #FASTSCSSBlock opposite: #childrenNodes',
		'#callExpressionOwner => FMOne type: #FASTSCSSCallExpression opposite: #childrenNodes',
		'#charsetStatementOwner => FMOne type: #FASTSCSSCharsetStatement opposite: #childrenNodes',
		'#childSelectorOwner => FMOne type: #FASTSCSSChildSelector opposite: #childrenNodes',
		'#classNameOwner => FMOne type: #FASTSCSSClassName opposite: #childrenNodes',
		'#classSelectorOwner => FMOne type: #FASTSCSSClassSelector opposite: #childrenNodes',
		'#debugStatementOwner => FMOne type: #FASTSCSSDebugStatement opposite: #childrenNodes',
		'#declarationOwner => FMOne type: #FASTSCSSDeclaration opposite: #childrenNodes',
		'#descendantSelectorOwner => FMOne type: #FASTSCSSDescendantSelector opposite: #childrenNodes',
		'#elseClauseOwner => FMOne type: #FASTSCSSElseClause opposite: #childrenNode',
		'#elseIfClauseConditionOwner => FMOne type: #FASTSCSSElseIfClause opposite: #condition',
		'#errorStatementOwner => FMOne type: #FASTSCSSErrorStatement opposite: #childrenNodes',
		'#extendStatementOwner => FMOne type: #FASTSCSSExtendStatement opposite: #childrenNodes',
		'#featureQueryOwner => FMOne type: #FASTSCSSFeatureQuery opposite: #childrenNodes',
		'#floatValueOwner => FMOne type: #FASTSCSSFloatValue opposite: #childrenNode',
		'#forStatementFromOwner => FMOne type: #FASTSCSSForStatement opposite: #from',
		'#forStatementThroughOwner => FMOne type: #FASTSCSSForStatement opposite: #through',
		'#forwardStatementOwner => FMOne type: #FASTSCSSForwardStatement opposite: #childrenNodes',
		'#genericChildren => FMMany type: #FASTSCSSEntity opposite: #genericParent',
		'#genericParent => FMOne type: #FASTSCSSEntity opposite: #genericChildren',
		'#gridValueOwner => FMOne type: #FASTSCSSGridValue opposite: #childrenNodes',
		'#idSelectorOwner => FMOne type: #FASTSCSSIdSelector opposite: #childrenNodes',
		'#ifStatementConditionOwner => FMOne type: #FASTSCSSIfStatement opposite: #condition',
		'#importStatementOwner => FMOne type: #FASTSCSSImportStatement opposite: #childrenNodes',
		'#includeStatementOwner => FMOne type: #FASTSCSSIncludeStatement opposite: #childrenNodes',
		'#integerValueOwner => FMOne type: #FASTSCSSIntegerValue opposite: #childrenNode',
		'#interpolationOwner => FMOne type: #FASTSCSSInterpolation opposite: #childrenNodes',
		'#keyframeBlockListOwner => FMOne type: #FASTSCSSKeyframeBlockList opposite: #childrenNodes',
		'#keyframeBlockOwner => FMOne type: #FASTSCSSKeyframeBlock opposite: #childrenNodes',
		'#keyframesStatementOwner => FMOne type: #FASTSCSSKeyframesStatement opposite: #childrenNodes',
		'#listValueOwner => FMOne type: #FASTSCSSListValue opposite: #childrenNodes',
		'#mediaStatementOwner => FMOne type: #FASTSCSSMediaStatement opposite: #childrenNodes',
		'#namespaceSelectorOwner => FMOne type: #FASTSCSSNamespaceSelector opposite: #childrenNodes',
		'#namespaceStatementOwner => FMOne type: #FASTSCSSNamespaceStatement opposite: #childrenNodes',
		'#parameterDefaultOwner => FMOne type: #FASTSCSSParameter opposite: #default',
		'#parametersOwner => FMOne type: #FASTSCSSParameters opposite: #childrenNodes',
		'#parenthesizedQueryOwner => FMOne type: #FASTSCSSParenthesizedQuery opposite: #childrenNode',
		'#parenthesizedValueOwner => FMOne type: #FASTSCSSParenthesizedValue opposite: #childrenNodes',
		'#placeholderOwner => FMOne type: #FASTSCSSPlaceholder opposite: #childrenNode',
		'#postcssStatementOwner => FMOne type: #FASTSCSSPostcssStatement opposite: #childrenNodes',
		'#propertyNameOwner => FMOne type: #FASTSCSSPropertyName opposite: #childrenNodes',
		'#pseudoClassSelectorOwner => FMOne type: #FASTSCSSPseudoClassSelector opposite: #childrenNodes',
		'#pseudoElementSelectorOwner => FMOne type: #FASTSCSSPseudoElementSelector opposite: #childrenNodes',
		'#returnStatementOwner => FMOne type: #FASTSCSSReturnStatement opposite: #childrenNodes',
		'#ruleSetOwner => FMOne type: #FASTSCSSRuleSet opposite: #childrenNodes',
		'#selectorQueryOwner => FMOne type: #FASTSCSSSelectorQuery opposite: #childrenNode',
		'#selectorsOwner => FMOne type: #FASTSCSSSelectors opposite: #childrenNodes',
		'#siblingSelectorOwner => FMOne type: #FASTSCSSSiblingSelector opposite: #childrenNodes',
		'#stylesheetOwner => FMOne type: #FASTSCSSStylesheet opposite: #childrenNodes',
		'#supportsStatementOwner => FMOne type: #FASTSCSSSupportsStatement opposite: #childrenNodes',
		'#tagNameOwner => FMOne type: #FASTSCSSTagName opposite: #childrenNodes',
		'#unaryQueryOwner => FMOne type: #FASTSCSSUnaryQuery opposite: #childrenNode',
		'#useStatementOwner => FMOne type: #FASTSCSSUseStatement opposite: #childrenNodes',
		'#warnStatementOwner => FMOne type: #FASTSCSSWarnStatement opposite: #childrenNodes',
		'#whileStatementOwner => FMOne type: #FASTSCSSWhileStatement opposite: #childrenNodes'
	],
	#category : 'FAST-SCSS-Model-Entities',
	#package : 'FAST-SCSS-Model',
	#tag : 'Entities'
}

{ #category : 'meta' }
FASTSCSSEntity class >> annotation [

	<ignoreForCoverage>
	<FMClass: #Entity super: #MooseEntity>
	<package: #'FAST-SCSS-Model'>
	<generated>
	<abstract>
]

{ #category : 'testing' }
FASTSCSSEntity class >> isAbstract [

	<ignoreForCoverage>
	<generated>
	^ self == FASTSCSSEntity
]

{ #category : 'meta' }
FASTSCSSEntity class >> metamodel [

	<ignoreForCoverage>
	<generated>
	^ FASTSCSSModel metamodel
]

{ #category : 'adding' }
FASTSCSSEntity >> addGenericChild: anObject [

	<ignoreForCoverage>
	<generated>
	^ self genericChildren add: anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> adjacentSiblingSelectorOwner [
	"Relation named: #adjacentSiblingSelectorOwner type: #FASTSCSSAdjacentSiblingSelector opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ adjacentSiblingSelectorOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> adjacentSiblingSelectorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	adjacentSiblingSelectorOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> argumentValueOwner [
	"Relation named: #argumentValueOwner type: #FASTSCSSArgument opposite: #value"

	<ignoreForCoverage>
	<generated>
	<container>
	^ argumentValueOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> argumentValueOwner: anObject [

	<ignoreForCoverage>
	<generated>
	argumentValueOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> argumentsOwner [
	"Relation named: #argumentsOwner type: #FASTSCSSArguments opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ argumentsOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> argumentsOwner: anObject [

	<ignoreForCoverage>
	<generated>
	argumentsOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> atRootStatementOwner [
	"Relation named: #atRootStatementOwner type: #FASTSCSSAtRootStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ atRootStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> atRootStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	atRootStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> atRuleOwner [
	"Relation named: #atRuleOwner type: #FASTSCSSAtRule opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ atRuleOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> atRuleOwner: anObject [

	<ignoreForCoverage>
	<generated>
	atRuleOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> attributeNameOwner [
	"Relation named: #attributeNameOwner type: #FASTSCSSAttributeName opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ attributeNameOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> attributeNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	attributeNameOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> attributeSelectorOwner [
	"Relation named: #attributeSelectorOwner type: #FASTSCSSAttributeSelector opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ attributeSelectorOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> attributeSelectorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	attributeSelectorOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> binaryExpressionOwner [
	"Relation named: #binaryExpressionOwner type: #FASTSCSSBinaryExpression opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ binaryExpressionOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> binaryExpressionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	binaryExpressionOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> binaryQueryOwner [
	"Relation named: #binaryQueryOwner type: #FASTSCSSBinaryQuery opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ binaryQueryOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> binaryQueryOwner: anObject [

	<ignoreForCoverage>
	<generated>
	binaryQueryOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> blockOwner [
	"Relation named: #blockOwner type: #FASTSCSSBlock opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ blockOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> blockOwner: anObject [

	<ignoreForCoverage>
	<generated>
	blockOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> callExpressionOwner [
	"Relation named: #callExpressionOwner type: #FASTSCSSCallExpression opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ callExpressionOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> callExpressionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	callExpressionOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> charsetStatementOwner [
	"Relation named: #charsetStatementOwner type: #FASTSCSSCharsetStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ charsetStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> charsetStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	charsetStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> childSelectorOwner [
	"Relation named: #childSelectorOwner type: #FASTSCSSChildSelector opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ childSelectorOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> childSelectorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	childSelectorOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> classNameOwner [
	"Relation named: #classNameOwner type: #FASTSCSSClassName opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ classNameOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> classNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	classNameOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> classSelectorOwner [
	"Relation named: #classSelectorOwner type: #FASTSCSSClassSelector opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ classSelectorOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> classSelectorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	classSelectorOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> debugStatementOwner [
	"Relation named: #debugStatementOwner type: #FASTSCSSDebugStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ debugStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> debugStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	debugStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> declarationOwner [
	"Relation named: #declarationOwner type: #FASTSCSSDeclaration opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ declarationOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> declarationOwner: anObject [

	<ignoreForCoverage>
	<generated>
	declarationOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> descendantSelectorOwner [
	"Relation named: #descendantSelectorOwner type: #FASTSCSSDescendantSelector opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ descendantSelectorOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> descendantSelectorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	descendantSelectorOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> elseClauseOwner [
	"Relation named: #elseClauseOwner type: #FASTSCSSElseClause opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ elseClauseOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> elseClauseOwner: anObject [

	<ignoreForCoverage>
	<generated>
	elseClauseOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> elseIfClauseConditionOwner [
	"Relation named: #elseIfClauseConditionOwner type: #FASTSCSSElseIfClause opposite: #condition"

	<ignoreForCoverage>
	<generated>
	<container>
	^ elseIfClauseConditionOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> elseIfClauseConditionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	elseIfClauseConditionOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> errorStatementOwner [
	"Relation named: #errorStatementOwner type: #FASTSCSSErrorStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ errorStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> errorStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	errorStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> extendStatementOwner [
	"Relation named: #extendStatementOwner type: #FASTSCSSExtendStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ extendStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> extendStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	extendStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> featureQueryOwner [
	"Relation named: #featureQueryOwner type: #FASTSCSSFeatureQuery opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ featureQueryOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> featureQueryOwner: anObject [

	<ignoreForCoverage>
	<generated>
	featureQueryOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> floatValueOwner [
	"Relation named: #floatValueOwner type: #FASTSCSSFloatValue opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ floatValueOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> floatValueOwner: anObject [

	<ignoreForCoverage>
	<generated>
	floatValueOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> forStatementFromOwner [
	"Relation named: #forStatementFromOwner type: #FASTSCSSForStatement opposite: #from"

	<ignoreForCoverage>
	<generated>
	<container>
	^ forStatementFromOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> forStatementFromOwner: anObject [

	<ignoreForCoverage>
	<generated>
	forStatementFromOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> forStatementThroughOwner [
	"Relation named: #forStatementThroughOwner type: #FASTSCSSForStatement opposite: #through"

	<ignoreForCoverage>
	<generated>
	<container>
	^ forStatementThroughOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> forStatementThroughOwner: anObject [

	<ignoreForCoverage>
	<generated>
	forStatementThroughOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> forwardStatementOwner [
	"Relation named: #forwardStatementOwner type: #FASTSCSSForwardStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ forwardStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> forwardStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	forwardStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> genericChildren [
	"Relation named: #genericChildren type: #FASTSCSSEntity opposite: #genericParent"

	<ignoreForCoverage>
	<generated>
	<derived>
	^ genericChildren
]

{ #category : 'accessing' }
FASTSCSSEntity >> genericChildren: anObject [

	<ignoreForCoverage>
	<generated>
	genericChildren value: anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> genericParent [
	"Relation named: #genericParent type: #FASTSCSSEntity opposite: #genericChildren"

	<ignoreForCoverage>
	<generated>
	<container>
	^ genericParent
]

{ #category : 'accessing' }
FASTSCSSEntity >> genericParent: anObject [

	<ignoreForCoverage>
	<generated>
	genericParent := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> gridValueOwner [
	"Relation named: #gridValueOwner type: #FASTSCSSGridValue opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ gridValueOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> gridValueOwner: anObject [

	<ignoreForCoverage>
	<generated>
	gridValueOwner := anObject
]

{ #category : 'testing' }
FASTSCSSEntity >> hasImmediateSource [

	<ignoreForCoverage>
	<generated>
	^ false
]

{ #category : 'accessing' }
FASTSCSSEntity >> idSelectorOwner [
	"Relation named: #idSelectorOwner type: #FASTSCSSIdSelector opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ idSelectorOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> idSelectorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	idSelectorOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> ifStatementConditionOwner [
	"Relation named: #ifStatementConditionOwner type: #FASTSCSSIfStatement opposite: #condition"

	<ignoreForCoverage>
	<generated>
	<container>
	^ ifStatementConditionOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> ifStatementConditionOwner: anObject [

	<ignoreForCoverage>
	<generated>
	ifStatementConditionOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> importStatementOwner [
	"Relation named: #importStatementOwner type: #FASTSCSSImportStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ importStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> importStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	importStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> includeStatementOwner [
	"Relation named: #includeStatementOwner type: #FASTSCSSIncludeStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ includeStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> includeStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	includeStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> integerValueOwner [
	"Relation named: #integerValueOwner type: #FASTSCSSIntegerValue opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ integerValueOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> integerValueOwner: anObject [

	<ignoreForCoverage>
	<generated>
	integerValueOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> interpolationOwner [
	"Relation named: #interpolationOwner type: #FASTSCSSInterpolation opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ interpolationOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> interpolationOwner: anObject [

	<ignoreForCoverage>
	<generated>
	interpolationOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> keyframeBlockListOwner [
	"Relation named: #keyframeBlockListOwner type: #FASTSCSSKeyframeBlockList opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ keyframeBlockListOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> keyframeBlockListOwner: anObject [

	<ignoreForCoverage>
	<generated>
	keyframeBlockListOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> keyframeBlockOwner [
	"Relation named: #keyframeBlockOwner type: #FASTSCSSKeyframeBlock opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ keyframeBlockOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> keyframeBlockOwner: anObject [

	<ignoreForCoverage>
	<generated>
	keyframeBlockOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> keyframesStatementOwner [
	"Relation named: #keyframesStatementOwner type: #FASTSCSSKeyframesStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ keyframesStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> keyframesStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	keyframesStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> listValueOwner [
	"Relation named: #listValueOwner type: #FASTSCSSListValue opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ listValueOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> listValueOwner: anObject [

	<ignoreForCoverage>
	<generated>
	listValueOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> mediaStatementOwner [
	"Relation named: #mediaStatementOwner type: #FASTSCSSMediaStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ mediaStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> mediaStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	mediaStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> namespaceSelectorOwner [
	"Relation named: #namespaceSelectorOwner type: #FASTSCSSNamespaceSelector opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ namespaceSelectorOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> namespaceSelectorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	namespaceSelectorOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> namespaceStatementOwner [
	"Relation named: #namespaceStatementOwner type: #FASTSCSSNamespaceStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ namespaceStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> namespaceStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	namespaceStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> parameterDefaultOwner [
	"Relation named: #parameterDefaultOwner type: #FASTSCSSParameter opposite: #default"

	<ignoreForCoverage>
	<generated>
	<container>
	^ parameterDefaultOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> parameterDefaultOwner: anObject [

	<ignoreForCoverage>
	<generated>
	parameterDefaultOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> parametersOwner [
	"Relation named: #parametersOwner type: #FASTSCSSParameters opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ parametersOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> parametersOwner: anObject [

	<ignoreForCoverage>
	<generated>
	parametersOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> parenthesizedQueryOwner [
	"Relation named: #parenthesizedQueryOwner type: #FASTSCSSParenthesizedQuery opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ parenthesizedQueryOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> parenthesizedQueryOwner: anObject [

	<ignoreForCoverage>
	<generated>
	parenthesizedQueryOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> parenthesizedValueOwner [
	"Relation named: #parenthesizedValueOwner type: #FASTSCSSParenthesizedValue opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ parenthesizedValueOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> parenthesizedValueOwner: anObject [

	<ignoreForCoverage>
	<generated>
	parenthesizedValueOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> placeholderOwner [
	"Relation named: #placeholderOwner type: #FASTSCSSPlaceholder opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ placeholderOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> placeholderOwner: anObject [

	<ignoreForCoverage>
	<generated>
	placeholderOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> postcssStatementOwner [
	"Relation named: #postcssStatementOwner type: #FASTSCSSPostcssStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ postcssStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> postcssStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	postcssStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> propertyNameOwner [
	"Relation named: #propertyNameOwner type: #FASTSCSSPropertyName opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ propertyNameOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> propertyNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	propertyNameOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> pseudoClassSelectorOwner [
	"Relation named: #pseudoClassSelectorOwner type: #FASTSCSSPseudoClassSelector opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ pseudoClassSelectorOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> pseudoClassSelectorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	pseudoClassSelectorOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> pseudoElementSelectorOwner [
	"Relation named: #pseudoElementSelectorOwner type: #FASTSCSSPseudoElementSelector opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ pseudoElementSelectorOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> pseudoElementSelectorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	pseudoElementSelectorOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> returnStatementOwner [
	"Relation named: #returnStatementOwner type: #FASTSCSSReturnStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ returnStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> returnStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	returnStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> ruleSetOwner [
	"Relation named: #ruleSetOwner type: #FASTSCSSRuleSet opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ ruleSetOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> ruleSetOwner: anObject [

	<ignoreForCoverage>
	<generated>
	ruleSetOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> selectorQueryOwner [
	"Relation named: #selectorQueryOwner type: #FASTSCSSSelectorQuery opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ selectorQueryOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> selectorQueryOwner: anObject [

	<ignoreForCoverage>
	<generated>
	selectorQueryOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> selectorsOwner [
	"Relation named: #selectorsOwner type: #FASTSCSSSelectors opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ selectorsOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> selectorsOwner: anObject [

	<ignoreForCoverage>
	<generated>
	selectorsOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> siblingSelectorOwner [
	"Relation named: #siblingSelectorOwner type: #FASTSCSSSiblingSelector opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ siblingSelectorOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> siblingSelectorOwner: anObject [

	<ignoreForCoverage>
	<generated>
	siblingSelectorOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> stylesheetOwner [
	"Relation named: #stylesheetOwner type: #FASTSCSSStylesheet opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ stylesheetOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> stylesheetOwner: anObject [

	<ignoreForCoverage>
	<generated>
	stylesheetOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> supportsStatementOwner [
	"Relation named: #supportsStatementOwner type: #FASTSCSSSupportsStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ supportsStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> supportsStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	supportsStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> tagNameOwner [
	"Relation named: #tagNameOwner type: #FASTSCSSTagName opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ tagNameOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> tagNameOwner: anObject [

	<ignoreForCoverage>
	<generated>
	tagNameOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> unaryQueryOwner [
	"Relation named: #unaryQueryOwner type: #FASTSCSSUnaryQuery opposite: #childrenNode"

	<ignoreForCoverage>
	<generated>
	<container>
	<derived>
	^ unaryQueryOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> unaryQueryOwner: anObject [

	<ignoreForCoverage>
	<generated>
	unaryQueryOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> useStatementOwner [
	"Relation named: #useStatementOwner type: #FASTSCSSUseStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ useStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> useStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	useStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> warnStatementOwner [
	"Relation named: #warnStatementOwner type: #FASTSCSSWarnStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ warnStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> warnStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	warnStatementOwner := anObject
]

{ #category : 'accessing' }
FASTSCSSEntity >> whileStatementOwner [
	"Relation named: #whileStatementOwner type: #FASTSCSSWhileStatement opposite: #childrenNodes"

	<ignoreForCoverage>
	<generated>
	<container>
	^ whileStatementOwner
]

{ #category : 'accessing' }
FASTSCSSEntity >> whileStatementOwner: anObject [

	<ignoreForCoverage>
	<generated>
	whileStatementOwner := anObject
]
